### ISSUE TITLE
Addressing Comment #1 - Years since publication

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#1]
1. Calculate total years of availability for all papers associated with every cluster ("availability") - need to add and return a metric representing the cumulative number of years that the papers associated with a cluster have been available. Some of the papers say they will be available in 2022 (meaning they just haven't been released by Pubmed yet) and should get availability = 0 (so should 2021). For example a cluster associated with 3 papers published in 1990, 2000, and 2010 should have availability = 31 + 21 + 11 = 63.

Add CPOF/availability as separate column
Add availability as separate column

"total_citations" is similarly structured to how availability should be.
https://github.com/sopeeweje/NLP-AI-Medicine/blob/3796eabdcd2f085783f33286d551d5abc6d3f4b7/analyze_clusters.py#L357-L375

2. It can be calculated here:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/ec388326c6d0d21d0735386b65ca8539d511b41b/analyze_clusters.py#L387-L395

3. Once this is done, availability will need to be returned as part of this CSV
https://github.com/sopeeweje/NLP-AI-Medicine/blob/3796eabdcd2f085783f33286d551d5abc6d3f4b7/analyze_clusters.py#L863-L869

We can then use this metric to change citations per funding dollar (CPOF) to CPOF adjusted for years since publication.

**Comment by sb1024** [comment]
Below is a preview of the relevant columns in final_data.csv (first 10 clusters). Let me know if these values seem reasonable to you, and if you want any adjustments.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/suzie/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/suzie/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Citations per $1mil   funding | Years of Availability | Citations per $1mil funding per year
-- | -- | --
99.38478 | 3187 | 0.031184
251.5087 | 14931 | 0.016845
205.1988 | 4268 | 0.048078
750.5615 | 9606 | 0.078135
1377.388 | 2450 | 0.562199
1084.63 | 13181 | 0.082287
1697.313 | 15455 | 0.109823
896.8198 | 8329 | 0.107674
248.9781 | 8719 | 0.028556
312.6824 | 2925 | 0.1069



</body>

</html>

**Comment by sopeeweje** [comment]
Seems reasonable - if you can, do a quick check of availability / number of papers (= average availability), I imagine it should come out to around 10 or something like that. Based on these values you can change citations per million to citations per thousand. Thanks!

**Comment by sb1024** [comment]
Average availability of all papers from (paper.csv) is 6.16 

I'll change "Citations per $1mil funding per year" to "Citations per thousand dollars of funding per year" -- but do you want the original "Citations per $1mil funding" column also changed to thousands also?

**Comment by sopeeweje** [comment]
The original column can still be millions (probably won't use it anymore but we can keep it for reference). Thanks!
