### ISSUE TITLE
Autogenerating Table 1

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#2]
If we end up rerunning the analysis it's been annoying to recreate table 1 by hand. It's pretty similar in content to the final CSV:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/3796eabdcd2f085783f33286d551d5abc6d3f4b7/analyze_clusters.py#L863-L869

It would be great to add an additional CSV return with each run ("table1.csv") that has things in this format, where description and application category are blank because they have to be manually specified:
![image](https://user-images.githubusercontent.com/58275563/133863129-f7a1c6b5-d061-42ad-a43e-e2b6cdfcb760.png)

**Comment by sb1024** [comment]
Here's a sample table1 that is generated: [table1.csv](https://github.com/sopeeweje/NLP-AI-Medicine/blob/suzie/results/10-04-2021--231011/table1.csv)

If it looks good I'll make a pull request & merge the changes (along with #5)

**Comment by sopeeweje** [comment]
Looks good
