### ISSUE TITLE
Addressing Comment #2 - Making Table 2 a figure

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#3]
Table 2 is currently a table of funding by year:
![image](https://user-images.githubusercontent.com/58275563/133863405-1528c02f-503f-4fad-96f5-7bcffdb272a6.png)

It would be great to convert it to a figure (using matplotlib) that kinda looks like this:
![image](https://user-images.githubusercontent.com/58275563/133863304-ddc1ad42-f796-4b8e-9e3b-4346c8d25907.png)
Where the bars are the total award value in each year and the line is the average award size in each year, plotted on separate y-axes. All of the relevant data is in the "by_year.csv". The code for this plot can go in a separate file

**Comment by sb1024** [comment]
See commit f1cb9ee3600b05a38e686fd16ff1dde2c8931343

Let me know if you want any particular changes!


![table2_figure](https://user-images.githubusercontent.com/23280633/133937763-b93af500-4680-445b-b600-56432800c1ff.png)

**Comment by sopeeweje** [comment]
This is amazing! Can you change number of awards to award size (value/number of awards)?

**Comment by sb1024** [comment]
![table2_figure](https://user-images.githubusercontent.com/23280633/133959149-60a95257-c74b-46f5-b595-3a2ad6622a92.png)

**Comment by sopeeweje** [comment]
Perfect
