### ISSUE TITLE
Addressing Comment #3 - Analysis by institute

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#4]
The end goal is to have a table that looks like this:
![image](https://user-images.githubusercontent.com/58275563/133864501-1a5f52de-7380-41cb-ac16-0dcdb45b38f4.png)

Avg. APT (95% CI) - "0.9 (0.85-0.95)"
CPOF/availability - "###.#"

Here's how we could get there. Data is saved from each award here, "administration" is the institute that gave the award:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/feature_extraction.py#L59-L71

Get papers by institute by doing the following:
1) Load data.pkl from the main directory (list of dictionaries representing each award). Use these lines to get the number of awards and total value of the awards by institute:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/feature_extraction.py#L167-L176

2) Group the awards by "administration", where project_number is the value of the "project_number" key in each awards dictionary (called "by_institute":
`{"Institute1": [project_number1, project_number2, ...] ,
"Institute2": [project_number1, project_number2, ...], ...}`

3) Steal these lines directly to get the info on the papers:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/analyze_clusters.py#L384-L397

"output" will be structured as:
`{PMID1: {citations: ###, apt: ###, project: ###, year: ###},
PMID2: {citations: ###, apt: ###, project: ###, year: ###}...,`
"project" is the project number for that paper, which corresponds to project_number above.

4)  Iterating over "by_institute": For each institute -> for each project_number "idd" ->
`papers_institute_citations = [output[key]["citations"] for key in output if output[key]["project"]==idd]`
`papers_institute_apt = [output[key]["apt"] for key in output if output[key]["project"]==idd]`
`papers_institute_availability = [output[key]["year"] for key in output if output[key]["project"]==idd]` ***list of years that will need to be converted to availability

5) Sum over each of these lists for each institute. 95% CI for APT can be calculated with:
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/analyze_clusters.py#L427-L430

6) Return a CSV that matches the above picture

This can all be done in an independent function in analyze_clusters.py

**Comment by sb1024** [comment]
Several of the funding institutes have invalid values because of: <2 projects, 0 availability

[Link to table](https://github.com/sopeeweje/NLP-AI-Medicine/blob/suzie/by_funder_detailed.csv) (I can't figure out how to insert it here)

Let me know how that looks generally & if you want adjustments to the table.

**Comment by sopeeweje** [comment]
Looks good 👍🏾
