### ISSUE TITLE
Addressing comment #4 - Analysis by funding mechanism

### ISSUE THREAD

**Issue by sopeeweje** [sopeeweje/NLP-AI-Diagnosis#5]
End goal is to add these columns to the final_result table:
![image](https://user-images.githubusercontent.com/58275563/133866153-d0ebbeef-5ddd-4402-9a1b-c652c062343c.png)

These represent the 6 most common NIH funding mechanisms (https://grants.nih.gov/grants/funding/funding_program.htm) in this dataset. How to do this (not the cleanest but the easiest):

1. In the function "get_clusters", add keys to the output dictionary "r01", "u01", etc.
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/analyze_clusters.py#L132-L141

2. Right after cluster_data (a list of dictionaries representing each award that is in a given cluster) is defined here, count the number of awards with mechanisms equal to one of the targets ("R01", "U01", R44", "U24", "R21", "U54") and divide by len(cluster_data). Access the mechanisms by data["ind"]["mechanism"]. Append each of these values to a list (r01_by_cluster, u01_by_cluster, etc.)
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/analyze_clusters.py#L80-L85

3. Return those lists in "output".

4. Create new columns in final_data.csv for each of these percentages
https://github.com/sopeeweje/NLP-AI-Medicine/blob/378991ac290e414e6ea01068d9b322b8fba51c3c/analyze_clusters.py#L639-L645

**Comment by sb1024** [comment]
Here's the updated output file: [final_data.csv](https://github.com/sopeeweje/NLP-AI-Medicine/blob/suzie/results/10-04-2021--231011/final_data.csv)

It has the blank Description & Category columns, as well as the mechanism columns at the end. Let me know if you want any changes

**Comment by sopeeweje** [comment]
Awesome, one more change for #11 - an empty column titled "Clinical/Technical"
